name: verifact_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.1.1
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^3.1.0
  speech_to_text: ^7.3.0 
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  logger: ^2.6.2
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.5.4
  google_fonts: ^7.0.0
  flutter_svg: ^2.2.3
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  auto_size_text: ^3.0.0
  lucide_icons_flutter: ^3.1.9
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  permission_handler: ^12.0.1
  skeletonizer: ^2.1.2
  google_mlkit_text_recognition: ^0.15.0
  flutter_overlay_window: ^0.5.0
  camera: ^0.11.3
  image_picker: ^1.2.1
  video_player: ^2.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/brands/
    - assets/logos/
    - assets/icons/verified.png
    - .env